import { randomUUID } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readFileSync, readlinkSync, renameSync } from "node:fs";
import path from "node:path";
import type { Logger } from "pino";
import { z } from "zod";

import { resolvePaseoHome } from "../paseo-home.js";
import { writePrivateFileAtomicSync } from "../private-files.js";

export const AGENT_PROCESS_REGISTRY_FILE = "agent-processes.json";

/**
 * How long a scoped child may sit unowned — i.e. after a daemon generation other
 * than the current one recorded it — before the reaper treats it as garbage and
 * stops it. Measured from `orphanedAt` (when a daemon first observed the entry
 * as unowned), NOT from `startedAt`: a long-running agent whose owner died
 * seconds ago must still get a full adoption window instead of losing its
 * record at the next bootstrap.
 */
export const AGENT_PROCESS_UNOWNED_RECORD_TTL_MS = 24 * 60 * 60 * 1000;

/** Grace between SIGTERM and SIGKILL when reaping an expired orphan. */
export const AGENT_PROCESS_ORPHAN_TERM_GRACE_MS = 2_000;
/** How long each signal is given to actually stop the process before giving up. */
export const AGENT_PROCESS_ORPHAN_KILL_TIMEOUT_MS = 5_000;
/** Poll interval while waiting for a signalled orphan to disappear. */
const ORPHAN_LIVENESS_POLL_MS = 25;

/**
 * Scope ids are generated by `buildAgentScopeInvocation` as
 * `paseo-agent-<spawning-daemon-pid>-<12 hex chars>`. Anything else in the
 * registry file is refused before anything is signalled: the unit name is
 * attacker-controllable data (a JSON file under `$PASEO_HOME`) and it is passed
 * to `systemctl --user kill`, so an unvalidated name would let a tampered
 * registry terminate an arbitrary user unit.
 */
const AGENT_SCOPE_ID_PATTERN = /^paseo-agent-\d+-[0-9a-f]{12}$/;

export const AgentProcessEntrySchema = z.object({
  scopeId: z.string().min(1),
  unit: z.string().min(1),
  pid: z.number().int().positive(),
  provider: z.string().min(1),
  sessionId: z.string().min(1).optional(),
  startedAt: z.string().min(1),
  // Generation of the daemon process that recorded the entry; absent on files
  // written before this field existed. Optional so old registries still parse.
  ownerDaemonId: z.string().min(1).optional(),
  // When a daemon first saw this entry as unowned. The orphan TTL runs from
  // here so a long-lived child is not expired by its own age.
  orphanedAt: z.string().min(1).optional(),
});

export type AgentProcessEntry = z.infer<typeof AgentProcessEntrySchema>;

const AgentProcessRegistrySchema = z.array(AgentProcessEntrySchema);

export interface AgentProcessRegistryOptions {
  filePath?: string;
  logger?: Logger;
}

export interface ReapResult {
  removed: AgentProcessEntry[];
  kept: AgentProcessEntry[];
}

export type AgentProcessClassification = "dead" | "recycled" | "live-matching";

let registryHomeOverride: string | null = null;

/**
 * Outcome of a registry read that distinguishes "there is nothing recorded"
 * (ENOENT) from "the file exists but I could not use it".
 *
 * The distinction is load-bearing: a writer that treats EACCES/EIO/corruption
 * as "empty registry" writes back only its own new entry, silently erasing
 * every other live child's record and making those processes untrackable.
 */
export type AgentProcessRegistryReadResult =
  | { ok: true; entries: AgentProcessEntry[]; quarantinedPath?: string }
  | { ok: false; reason: "unreadable"; error: unknown };

/**
 * Pin the registry to one daemon home. `createPaseoDaemon` calls this with
 * `config.paseoHome` so spawn-time recording and startup reaping agree on the
 * daemon's home even when tests pass an explicit `paseoHome` without setting
 * `PASEO_HOME` in the environment. Pass `null` to fall back to env resolution.
 */
export function setAgentProcessRegistryHome(home: string | null): void {
  registryHomeOverride = home;
}

/**
 * Registry path follows the daemon's home so spawn-time recording and startup
 * reaping always agree on one file.
 */
export function resolveAgentProcessRegistryPath(): string {
  return path.join(registryHomeOverride ?? resolvePaseoHome(), AGENT_PROCESS_REGISTRY_FILE);
}

/**
 * Identity of the daemon process recording entries right now. One random value
 * per process: after a daemon restart every existing record belongs to a
 * previous generation, which is what lets the reaper tell this daemon's live
 * records apart from unowned orphans.
 */
const ownerDaemonId = randomUUID();

export function getAgentProcessOwnerDaemonId(): string {
  return ownerDaemonId;
}

/**
 * Move an unusable registry aside instead of overwriting it, so the corrupt
 * content survives for an operator while the next write starts clean.
 */
function quarantineCorruptRegistry(filePath: string, logger?: Logger): string | undefined {
  // The random suffix keeps two corrupt snapshots in the same millisecond from
  // colliding on one name (rename would silently discard the first).
  const quarantinedPath = `${filePath}.corrupt-${Date.now()}-${randomUUID().slice(0, 8)}`;
  try {
    renameSync(filePath, quarantinedPath);
    logger?.error(
      { filePath, quarantinedPath },
      "Agent process registry was unreadable; moved aside so live records are not overwritten",
    );
    return quarantinedPath;
  } catch (error) {
    logger?.error(
      { err: error, filePath },
      "Failed to move corrupt agent process registry aside; refusing to overwrite it",
    );
    return undefined;
  }
}

/**
 * Strict read: ENOENT and corrupt content are recoverable (empty / quarantined),
 * but an I/O or permission failure is an error the caller must not paper over
 * by writing a registry that contains only its own entry.
 */
function readAgentProcessRegistryStrict(
  options: AgentProcessRegistryOptions = {},
): AgentProcessRegistryReadResult {
  const filePath = options.filePath ?? resolveAgentProcessRegistryPath();
  const logger = options.logger;
  let raw: string;
  try {
    raw = readFileSync(filePath, "utf8");
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    if (code === "ENOENT" || code === "ENOTDIR") {
      return { ok: true, entries: [] };
    }
    return { ok: false, reason: "unreadable", error };
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    logger?.error({ filePath }, "Agent process registry is not valid JSON");
    const quarantinedPath = quarantineCorruptRegistry(filePath, logger);
    return quarantinedPath
      ? { ok: true, entries: [], quarantinedPath }
      : { ok: false, reason: "unreadable", error: new Error("corrupt registry") };
  }
  const result = AgentProcessRegistrySchema.safeParse(parsed);
  if (!result.success) {
    logger?.error(
      { filePath, issues: result.error.issues },
      "Agent process registry has an unexpected shape",
    );
    const quarantinedPath = quarantineCorruptRegistry(filePath, logger);
    return quarantinedPath
      ? { ok: true, entries: [], quarantinedPath }
      : { ok: false, reason: "unreadable", error: result.error };
  }
  return { ok: true, entries: result.data };
}

/**
 * Read the registry. A missing file yields []; a corrupt file is moved aside
 * (also yielding []); an unreadable-but-present file yields [] as well so
 * read-only callers keep working, but writers use the strict form above and
 * refuse to write over it.
 */
export function readAgentProcessRegistry(
  options: AgentProcessRegistryOptions = {},
): AgentProcessEntry[] {
  const read = readAgentProcessRegistryStrict(options);
  if (read.ok) {
    return read.entries;
  }
  options.logger?.warn(
    { err: read.error, filePath: options.filePath ?? resolveAgentProcessRegistryPath() },
    "Failed to read agent process registry",
  );
  return [];
}

/**
 * Write the registry durably: the payload is fsync'd before the rename so a
 * crash cannot leave a renamed-but-empty file that would erase every record.
 */
function writeAgentProcessRegistryFile(filePath: string, entries: AgentProcessEntry[]): void {
  writePrivateFileAtomicSync(filePath, `${JSON.stringify(entries, null, 2)}\n`, { fsync: true });
}

/**
 * Add (or replace) the entry for a pid. Never throws: on any failure the
 * registry simply has no entry recorded.
 */
export function recordAgentProcess(
  entry: AgentProcessEntry,
  options: AgentProcessRegistryOptions = {},
): boolean {
  const filePath = options.filePath ?? resolveAgentProcessRegistryPath();
  const logger = options.logger;
  try {
    const validated = AgentProcessEntrySchema.parse(entry);
    // Stamp the recording daemon so startup reaping can tell this daemon's own
    // records from entries whose owning daemon generation is gone.
    const stamped: AgentProcessEntry = {
      ...validated,
      ownerDaemonId: validated.ownerDaemonId ?? ownerDaemonId,
    };
    const current = readAgentProcessRegistryStrict({ filePath, logger });
    if (!current.ok) {
      // Writing now would replace a registry we could not read with a
      // single-entry file, erasing every other live child's record.
      logger?.error(
        { err: current.error, filePath, pid: entry.pid },
        "Refusing to record agent process: registry unreadable, existing records preserved",
      );
      return false;
    }
    const next = current.entries.filter((existing) => existing.pid !== stamped.pid);
    next.push(stamped);
    writeAgentProcessRegistryFile(filePath, next);
    return true;
  } catch (error) {
    logger?.warn({ err: error, filePath, pid: entry.pid }, "Failed to record agent process");
    return false;
  }
}

/**
 * Drop the entry for a pid (idempotent). Never throws.
 */
export function forgetAgentProcess(
  pid: number,
  options: AgentProcessRegistryOptions = {},
): boolean {
  const filePath = options.filePath ?? resolveAgentProcessRegistryPath();
  const logger = options.logger;
  try {
    const current = readAgentProcessRegistryStrict({ filePath, logger });
    if (!current.ok) {
      logger?.error(
        { err: current.error, filePath, pid },
        "Refusing to forget agent process: registry unreadable, existing records preserved",
      );
      return false;
    }
    const next = current.entries.filter((entry) => entry.pid !== pid);
    if (next.length === current.entries.length) {
      return true;
    }
    writeAgentProcessRegistryFile(filePath, next);
    return true;
  } catch (error) {
    logger?.warn({ err: error, filePath, pid }, "Failed to forget agent process");
    return false;
  }
}

export function isPidAlive(pid: number): boolean {
  if (!Number.isInteger(pid) || pid <= 0) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch (error) {
    // EPERM means the pid exists but belongs to another user — still alive.
    return (error as NodeJS.ErrnoException).code === "EPERM";
  }
}

/**
 * A zombie still answers `kill(pid, 0)`, but it holds no memory, no fds and no
 * CPU and it is already dead for every purpose that matters here: it will never
 * run another instruction and its parent (or init) reaps it without help. A
 * signalled orphan that has become a zombie has therefore been stopped, and
 * waiting any longer would only block the reaper for nothing.
 */
export function isPidZombie(pid: number): boolean {
  if (process.platform !== "linux") return false;
  try {
    const stat = readFileSync(`/proc/${pid}/stat`, "utf8");
    // "pid (comm) state" — comm can contain spaces and parentheses, so the
    // state letter is the one after the final ')'.
    const closing = stat.lastIndexOf(")");
    if (closing < 0) return false;
    return stat
      .slice(closing + 1)
      .trim()
      .startsWith("Z");
  } catch {
    return false;
  }
}

/** True only while the process can still consume CPU. */
export function isPidRunning(pid: number): boolean {
  return isPidAlive(pid) && !isPidZombie(pid);
}

/**
 * Whether this entry's unit may be signalled. The name is data read from a JSON
 * file under `$PASEO_HOME` and is handed to `systemctl --user kill`, so an
 * unvalidated name would let a tampered registry terminate an arbitrary user
 * unit. Only the exact shape `buildAgentScopeInvocation` generates is accepted,
 * and the unit must be that scope's own unit.
 */
export function isSignalableAgentScopeUnit(entry: AgentProcessEntry): boolean {
  return AGENT_SCOPE_ID_PATTERN.test(entry.scopeId) && entry.unit === `${entry.scopeId}.scope`;
}

export type AgentScopeKillSignal = "SIGTERM" | "SIGKILL";

export interface AgentScopeKillResult {
  stopped: boolean;
  reason: string;
}

export interface AgentScopeKillOptions {
  logger?: Logger;
  /** Test seam for the unit kill. Defaults to `systemctl --user kill`. */
  killScope?: (unit: string, signal: AgentScopeKillSignal) => void;
  termGraceMs?: number;
  killTimeoutMs?: number;
  /** Test seam for the bounded synchronous wait. */
  sleepMs?: (ms: number) => void;
  /** Test seam for the post-kill liveness check. */
  isRunning?: (pid: number) => boolean;
}

/**
 * Blocking sleep. The reaper is synchronous (it runs inline during bootstrap),
 * so waiting for a signalled orphan to disappear cannot be async.
 */
function sleepSync(ms: number): void {
  if (ms <= 0) return;
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}

/**
 * True when the pid is positively proven to be a member of its recorded scope
 * cgroup. Used to gate the `process.kill` fallback: signalling by unit needs
 * only the unit-name check, but signalling by pid must not be reachable for an
 * entry whose identity is merely a cmdline marker.
 */
function hasVerifiedScopeMembership(entry: AgentProcessEntry): boolean {
  const cgroup = readProcessCgroup(entry.pid);
  return cgroup !== null && cgroupHasScope(cgroup, entry.scopeId);
}

function killScopeUnitViaSystemd(unit: string, signal: AgentScopeKillSignal): void {
  // `systemctl stop` is a documented no-op for scope units (verified on systemd
  // 259: it exits 0 and the process keeps running), so the only primitive that
  // actually stops a scope is `systemctl kill`.
  execFileSync("systemctl", ["--user", "kill", "--kill-whom=all", `--signal=${signal}`, unit], {
    stdio: ["ignore", "ignore", "pipe"],
    timeout: 10_000,
  });
}

function waitForExit(
  entry: AgentProcessEntry,
  timeoutMs: number,
  isRunning: (pid: number) => boolean,
  sleepMs: (ms: number) => void,
): boolean {
  const deadline = Date.now() + timeoutMs;
  // Check first: a process that dies instantly must not cost one poll interval.
  while (isRunning(entry.pid)) {
    if (Date.now() >= deadline) {
      return false;
    }
    sleepMs(ORPHAN_LIVENESS_POLL_MS);
  }
  return true;
}

type KillFn = (unit: string, signal: AgentScopeKillSignal) => void;

/**
 * Stop one expired orphan for good: SIGTERM the whole scope, wait out a grace
 * period, then SIGKILL whatever is left. Signalling is scoped to the unit's
 * cgroup so any children the provider spawned die with it.
 *
 * Returns `stopped: true` only after the pid is confirmed gone. The caller must
 * keep the record when this returns false — a record whose process is still
 * alive is the untrackable leak this whole path exists to prevent.
 */
export function stopExpiredAgentScope(
  entry: AgentProcessEntry,
  options: AgentScopeKillOptions = {},
): AgentScopeKillResult {
  const logger = options.logger;
  const isRunning = options.isRunning ?? isPidRunning;
  const sleepMs = options.sleepMs ?? sleepSync;
  const termGraceMs = options.termGraceMs ?? AGENT_PROCESS_ORPHAN_TERM_GRACE_MS;
  const killTimeoutMs = options.killTimeoutMs ?? AGENT_PROCESS_ORPHAN_KILL_TIMEOUT_MS;

  if (!isSignalableAgentScopeUnit(entry)) {
    const reason = `refusing to signal ${JSON.stringify(entry.unit)}: not a scope unit this daemon created`;
    logger?.error(
      { unit: entry.unit, scopeId: entry.scopeId, pid: entry.pid, reason: "untrusted-unit-name" },
      reason,
    );
    return { stopped: false, reason };
  }
  if (!isRunning(entry.pid)) {
    return { stopped: true, reason: "already gone" };
  }

  const useSystemctl = options.killScope === undefined;
  const killScope: KillFn = options.killScope ?? killScopeUnitViaSystemd;
  const signal = makeUnitSignaller(
    entry,
    killScope,
    useSystemctl ? "systemctl" : "injected",
    logger,
  );

  let lastError = signal("SIGTERM");
  if (waitForExit(entry, termGraceMs, isRunning, sleepMs)) {
    return { stopped: true, reason: "terminated with SIGTERM" };
  }

  // systemctl is unavailable or refused. Fall back to signalling the pid
  // itself, but only when the entry's identity is cgroup-proven — a cmdline
  // marker alone must never authorise a kill.
  if (useSystemctl && lastError === null && hasVerifiedScopeMembership(entry)) {
    lastError = signalPidDirectly(entry, "SIGTERM", logger);
    if (waitForExit(entry, termGraceMs, isRunning, sleepMs)) {
      return { stopped: true, reason: "terminated with SIGTERM via pid fallback" };
    }
  }

  lastError = signal("SIGKILL") ?? lastError;
  if (waitForExit(entry, killTimeoutMs, isRunning, sleepMs)) {
    return { stopped: true, reason: "terminated with SIGKILL" };
  }
  return {
    stopped: false,
    reason: lastError ?? "orphan survived SIGTERM and SIGKILL",
  };
}

function makeUnitSignaller(
  entry: AgentProcessEntry,
  killScope: KillFn,
  via: string,
  logger?: Logger,
): (signal: AgentScopeKillSignal) => string | null {
  return (signal) => {
    try {
      killScope(entry.unit, signal);
      return null;
    } catch (error) {
      const detail = `systemctl --user kill ${signal} failed: ${String(error)}`;
      logger?.warn({ err: error, unit: entry.unit, pid: entry.pid, signal, via }, detail);
      return detail;
    }
  };
}

function signalPidDirectly(
  entry: AgentProcessEntry,
  signal: NodeJS.Signals,
  logger?: Logger,
): string | null {
  try {
    process.kill(entry.pid, signal);
    return null;
  } catch (error) {
    const detail = `process.kill ${signal} failed: ${String(error)}`;
    logger?.warn({ err: error, pid: entry.pid, signal }, detail);
    return detail;
  }
}

interface ProcessIdentity {
  cmdline: string;
  comm: string;
  exe: string;
}

/**
 * Best-effort identity read, same idea as deploy/systemd/paseo-prestart.sh:
 * cmdline + comm (+ exe) is what a recycled pid cannot fake.
 */
function readProcessIdentity(pid: number): ProcessIdentity | null {
  const base = `/proc/${pid}`;
  try {
    const cmdline = readFileSync(`${base}/cmdline`, "utf8").replaceAll("\u0000", " ").trim();
    const comm = readFileSync(`${base}/comm`, "utf8").trim();
    let exe = "";
    try {
      exe = readlinkSync(`${base}/exe`);
    } catch {
      // exe is a symlink that can vanish or be unreadable; it is only extra evidence.
    }
    return { cmdline, comm, exe };
  } catch {
    return null;
  }
}

function matchesProviderMarker(identity: ProcessIdentity, provider: string): boolean {
  const needle = provider.trim().toLowerCase();
  if (!needle) return false;
  const haystack = `${identity.cmdline} ${identity.comm} ${identity.exe}`.toLowerCase();
  return haystack.includes(needle);
}

/**
 * Reads `/proc/<pid>/cgroup`. Overridable in tests: a real process cannot be
 * placed inside a fabricated scope cgroup, so scope-membership scenarios are
 * driven through this reader while liveness and cmdline stay real.
 */
type ProcessCgroupReader = (pid: number) => string | null;

let cgroupReaderOverride: ProcessCgroupReader | null = null;

export function __setAgentProcessCgroupReaderForTests(reader: ProcessCgroupReader | null): void {
  cgroupReaderOverride = reader;
}

function readCgroupDirect(pid: number): string | null {
  try {
    return readFileSync(`/proc/${pid}/cgroup`, "utf8");
  } catch {
    return null;
  }
}

function readProcessCgroup(pid: number): string | null {
  if (cgroupReaderOverride) return cgroupReaderOverride(pid);
  return readCgroupDirect(pid);
}

/**
 * Scope unit name this process itself lives in, or null when it is not in a
 * scope (the normal case: the daemon runs in its unit cgroup). Read from the
 * real /proc, never through the test override. A recorded child spawned by
 * this very process shares our scope; that must not count as "foreign scope".
 * The test runner can itself run inside a scoped agent child, and probes it
 * spawns inherit that scope — treating it as recycled would break marker-based
 * classification in exactly the agent-driven workflow this feature targets.
 */
let ownProcessScope: string | null | undefined;

function getOwnProcessScope(): string | null {
  if (ownProcessScope === undefined) {
    ownProcessScope = extractScopeUnit(readCgroupDirect(process.pid));
  }
  return ownProcessScope;
}

/** First `<name>.scope` path segment in a cgroup text, or null. */
function extractScopeUnit(cgroup: string | null): string | null {
  if (cgroup === null) return null;
  const match = /(?:^|[/\n])([A-Za-z0-9_.:-]+\.scope)(?=[/\n]|$)/.exec(cgroup);
  return match ? match[1] : null;
}

/**
 * True when the pid is a member of the expected transient scope unit. A scope
 * is created only by `spawnInAgentScope`, and a recycled pid cannot fake
 * membership in its cgroup — this is the authoritative child identity.
 */
function cgroupHasScope(cgroup: string, scopeId: string): boolean {
  return cgroup.includes(`${scopeId}.scope`);
}

/**
 * True when the pid belongs to some scope unit that is neither the expected
 * scope nor this process's own scope. Membership in a different scope proves
 * the pid is not the recorded child (a recorded child lives only in its own
 * scope).
 */
function hasForeignScope(cgroup: string, entry: AgentProcessEntry): boolean {
  const ownScope = getOwnProcessScope();
  const expected = `${entry.scopeId}.scope`;
  const pattern = /(?:^|[/\n])([A-Za-z0-9_.:-]+\.scope)(?=[/\n]|$)/g;
  for (const match of cgroup.matchAll(pattern)) {
    if (match[1] !== expected && match[1] !== ownScope) return true;
  }
  return false;
}

/**
 * Classify one registry entry:
 * - dead: pid is gone (or vanished mid-check / no cmdline — an exited zombie)
 * - live-matching: pid is alive and a member of the entry's expected scope
 * - recycled: pid is alive but provably not the recorded child
 *
 * Identity is decided by cgroup membership first: the ACP spawn site records
 * provider ids like `claude-acp` while launching a different binary
 * (`prefix.command`), so cmdline markers alone can misclassify a live child as
 * recycled and drop its record while the process keeps running. A live pid in
 * the expected scope is therefore never recycled, whatever its cmdline says.
 *
 * A pid in some other scope (not the expected one, not ours) is recycled — it
 * cannot be the recorded child.
 *
 * Marker fallback (cmdline + comm + exe contains the provider id) applies only
 * when scope membership cannot speak for the entry: the expected scope no
 * longer exists (legacy record, unit collected) and the pid carries no foreign
 * scope either. Best effort either way; never applies to a pid alive in its
 * expected scope.
 */
export function classifyAgentProcessEntry(entry: AgentProcessEntry): AgentProcessClassification {
  if (!isPidAlive(entry.pid)) return "dead";
  if (process.platform !== "linux") {
    // /proc is unavailable; liveness is all we can verify off Linux.
    return "live-matching";
  }
  const identity = readProcessIdentity(entry.pid);
  if (!identity) return "dead";
  if (!identity.cmdline) return "dead";
  const cgroup = readProcessCgroup(entry.pid);
  if (cgroup !== null) {
    if (cgroupHasScope(cgroup, entry.scopeId)) return "live-matching";
    if (hasForeignScope(cgroup, entry)) return "recycled";
  }
  return matchesProviderMarker(identity, entry.provider) ? "live-matching" : "recycled";
}

/** Flush outcome: records kept because the pid is alive, records dropped. */
export interface FlushResult {
  kept: AgentProcessEntry[];
  removed: AgentProcessEntry[];
}

/**
 * Detach-stop flush: drop entries whose pid is gone, keep every entry whose
 * pid is still alive (no provider-marker check — a live pid is enough to
 * guarantee the next daemon can look at it; its startup reap decides
 * live-vs-recycled). Never throws: a registry failure degrades to "nothing
 * flushed".
 */
export function flushLiveAgentProcesses(options: AgentProcessRegistryOptions = {}): FlushResult {
  const filePath = options.filePath ?? resolveAgentProcessRegistryPath();
  const logger = options.logger;
  try {
    const read = readAgentProcessRegistryStrict({ filePath, logger });
    if (!read.ok) {
      logger?.warn(
        { err: read.error, filePath },
        "Agent process registry flush skipped: registry unreadable, records preserved",
      );
      return { kept: [], removed: [] };
    }
    const entries = read.entries;
    const kept: AgentProcessEntry[] = [];
    const removed: AgentProcessEntry[] = [];
    for (const entry of entries) {
      (isPidAlive(entry.pid) ? kept : removed).push(entry);
    }
    if (removed.length > 0) {
      writeAgentProcessRegistryFile(filePath, kept);
    }
    logger?.info(
      { filePath, kept: kept.length, removed: removed.length },
      "Agent process registry flushed for detach stop",
    );
    return { kept, removed };
  } catch (error) {
    logger?.warn({ err: error, filePath }, "Agent process registry flush failed; continuing");
    return { kept: [], removed: [] };
  }
}

/**
 * Startup reaper, and the daemon's only bounded kill path for scoped children.
 *
 * Per entry:
 * - `dead` / `recycled` — drop the record, never signal. A recycled pid is alive
 *   but provably not the recorded child, so it is not ours to touch.
 * - `live-matching`, owned by this daemon — keep, never signal. This is a child
 *   of the running daemon; it may be a legitimately long-lived agent.
 * - `live-matching`, not owned by this daemon — stamp `orphanedAt` the first time
 *   we see it (the orphan clock starts now, not at `startedAt`) and keep it while
 *   it is inside the TTL. Past the TTL it is a genuine orphan: stop it, and only
 *   drop the record once the process is confirmed gone. If the kill fails the
 *   record is KEPT so the next reap retries — a live child must never lose its
 *   record, because that is exactly what makes it unkillable forever.
 *
 * Never throws: a registry failure degrades to "nothing reaped", never a crash.
 */
export function reapStaleAgentProcesses(
  options: AgentProcessRegistryOptions & AgentScopeKillOptions = {},
): ReapResult {
  const filePath = options.filePath ?? resolveAgentProcessRegistryPath();
  const logger = options.logger;
  try {
    const read = readAgentProcessRegistryStrict({ filePath, logger });
    if (!read.ok) {
      logger?.warn(
        { err: read.error, filePath },
        "Agent process registry reap skipped: registry unreadable, records preserved",
      );
      return { removed: [], kept: [] };
    }
    const removed: AgentProcessEntry[] = [];
    const kept: AgentProcessEntry[] = [];
    let restamped = false;
    for (const entry of read.entries) {
      const decision = decideReapForEntry(entry, { filePath, logger, kill: options });
      if (decision.disposition === "keep") {
        kept.push(decision.entry);
        restamped = restamped || decision.restamped;
        continue;
      }
      if (decision.disposition === "keep-unlogged") {
        kept.push(decision.entry);
        continue;
      }
      removed.push(decision.entry);
      restamped = true;
    }
    if (read.quarantinedPath !== undefined || removed.length > 0 || restamped) {
      writeAgentProcessRegistryFile(filePath, kept);
    }
    logger?.info(
      { filePath, removed: removed.length, kept: kept.length },
      "Agent process registry reaped",
    );
    return { removed, kept };
  } catch (error) {
    logger?.warn({ err: error, filePath }, "Agent process registry reap failed; continuing");
    return { removed: [], kept: [] };
  }
}

type ReapDecision =
  /** Keep the entry as-is (already logged, or nothing to say). */
  | { disposition: "keep-unlogged"; entry: AgentProcessEntry }
  /** Keep the entry, optionally with a fresh `orphanedAt` stamp. */
  | { disposition: "keep"; entry: AgentProcessEntry; restamped: boolean }
  /** The record can go: the process is gone, or was stopped first. */
  | { disposition: "remove"; entry: AgentProcessEntry };

function decideReapForEntry(
  entry: AgentProcessEntry,
  ctx: { filePath: string; logger?: Logger; kill: AgentScopeKillOptions },
): ReapDecision {
  const { filePath, logger } = ctx;
  const classification = classifyAgentProcessEntry(entry);
  if (classification !== "live-matching") {
    // dead / recycled: drop the record, never signal. A recycled pid is alive
    // but provably not the recorded child, so it is not ours to touch.
    logger?.info(
      { filePath, pid: entry.pid, provider: entry.provider, unit: entry.unit, classification },
      "Reaped stale agent process registry entry",
    );
    return { disposition: "remove", entry };
  }

  // Owned by this daemon: keep and never signal. This is a child of the running
  // daemon and may be a legitimately long-lived agent.
  if (entry.ownerDaemonId === ownerDaemonId) {
    return { disposition: "keep-unlogged", entry };
  }

  const now = Date.now();
  if (!entry.orphanedAt) {
    // First observation as unowned starts the orphan clock. Stamping on first
    // sight is what keeps a long-running child from being expired by its own age
    // in the very next bootstrap after its owner died.
    logger?.info(
      {
        filePath,
        scopeId: entry.scopeId,
        unit: entry.unit,
        pid: entry.pid,
        provider: entry.provider,
        startedAt: entry.startedAt,
        ttlMs: AGENT_PROCESS_UNOWNED_RECORD_TTL_MS,
        reason: "orphaned",
      },
      "Unowned agent scope record adopted as an orphan clock started",
    );
    return {
      disposition: "keep",
      entry: { ...entry, orphanedAt: new Date(now).toISOString() },
      restamped: true,
    };
  }

  const orphanAgeMs = now - Date.parse(entry.orphanedAt);
  if (Number.isFinite(orphanAgeMs) && orphanAgeMs <= AGENT_PROCESS_UNOWNED_RECORD_TTL_MS) {
    return { disposition: "keep-unlogged", entry };
  }

  const kill = stopExpiredAgentScope(entry, { ...ctx.kill, logger });
  const baseLog = {
    filePath,
    scopeId: entry.scopeId,
    unit: entry.unit,
    pid: entry.pid,
    provider: entry.provider,
    startedAt: entry.startedAt,
    orphanedAt: entry.orphanedAt,
    orphanAgeMs: Number.isFinite(orphanAgeMs) ? orphanAgeMs : null,
  };
  if (!kill.stopped) {
    // Keep the record: an orphan we could not stop is exactly the case where
    // deleting the bookkeeping would make it unkillable forever.
    logger?.error(
      { ...baseLog, reason: "orphan-kill-failed", detail: kill.reason },
      `Failed to stop expired agent scope orphan ${entry.unit} (pid ${entry.pid}); keeping its record for the next reap`,
    );
    return { disposition: "keep-unlogged", entry };
  }
  logger?.warn(
    { ...baseLog, stoppedBy: kill.reason, reason: "orphan-stopped" },
    `Stopped expired orphan agent scope ${entry.unit} (pid ${entry.pid}) and dropped its record`,
  );
  return { disposition: "remove", entry };
}
