import { randomUUID } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readlinkSync, renameSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { Logger } from "pino";
import { z } from "zod";

import { resolvePaseoHome } from "../paseo-home.js";
import { writePrivateFileAtomicSync } from "../private-files.js";

export const AGENT_PROCESS_REGISTRY_FILE = "agent-processes.json";

/**
 * How long a scoped child may sit unowned — i.e. after a daemon generation other
 * than the current one recorded it — before the reaper treats it as garbage and
 * stops it. Measured from `orphanedAt` (when a daemon first observed the entry
 * as unowned), NOT from `startedAt`: a long-running agent whose owner died
 * seconds ago must still get a full adoption window instead of losing its
 * record at the next bootstrap.
 */
export const AGENT_PROCESS_UNOWNED_RECORD_TTL_MS = 24 * 60 * 60 * 1000;

/** Grace between SIGTERM and SIGKILL when reaping an expired orphan. */
export const AGENT_PROCESS_ORPHAN_TERM_GRACE_MS = 2_000;
/** How long each signal is given to actually stop the process before giving up. */
export const AGENT_PROCESS_ORPHAN_KILL_TIMEOUT_MS = 5_000;
/** Poll interval while waiting for a signalled orphan to disappear. */
const ORPHAN_LIVENESS_POLL_MS = 25;

/**
 * Hard wall-clock budget for ONE reap pass at bootstrap. The reap is synchronous
 * (see `reapStaleAgentProcesses`) and nothing is being served yet, so a generous
 * budget costs nothing; it exists so an unbounded number of stuck entries cannot
 * stall startup for minutes.
 */
export const AGENT_PROCESS_REAP_BOOTSTRAP_BUDGET_MS = 15_000;

/**
 * Hard wall-clock budget for one periodic reap pass. The periodic pass runs on
 * the daemon's event loop, so it gets a small budget: an orphan that cannot be
 * stopped in this pass keeps its record and is retried on the next one. Two
 * seconds is never reached in practice — `waitForScopeEmpty` returns the moment
 * the cgroup empties, so a cooperative orphan is stopped in single-digit
 * milliseconds and a pass costs one `systemctl show` per recorded entry.
 */
export const AGENT_PROCESS_REAP_INTERVAL_BUDGET_MS = 2_000;

/** cgroup v2 unified mount point for the user session on Linux. */
const CGROUP_ROOT = "/sys/fs/cgroup";

/** Ceiling on `systemctl` output for a single `show` call. */
const SYSTEMCTL_MAX_BUFFER_BYTES = 1 << 20;

/**
 * Scope ids are generated by `buildAgentScopeInvocation` as
 * `paseo-agent-<spawning-daemon-pid>-<12 hex chars>`. Anything else in the
 * registry file is refused before anything is signalled: the unit name is
 * attacker-controllable data (a JSON file under `$PASEO_HOME`) and it is passed
 * to `systemctl --user kill`, so an unvalidated name would let a tampered
 * registry terminate an arbitrary user unit.
 */
const AGENT_SCOPE_ID_PATTERN = /^paseo-agent-\d+-[0-9a-f]{12}$/;

export const AgentProcessEntrySchema = z.object({
  scopeId: z.string().min(1),
  unit: z.string().min(1),
  pid: z.number().int().positive(),
  provider: z.string().min(1),
  sessionId: z.string().min(1).optional(),
  startedAt: z.string().min(1),
  // Generation of the daemon process that recorded the entry; absent on files
  // written before this field existed. Optional so old registries still parse.
  ownerDaemonId: z.string().min(1).optional(),
  // When a daemon first saw this entry as unowned. The orphan TTL runs from
  // here so a long-lived child is not expired by its own age.
  orphanedAt: z.string().min(1).optional(),
});

export type AgentProcessEntry = z.infer<typeof AgentProcessEntrySchema>;

const AgentProcessRegistrySchema = z.array(AgentProcessEntrySchema);

export interface AgentProcessRegistryOptions {
  filePath?: string;
  logger?: Logger;
}

export interface ReapResult {
  removed: AgentProcessEntry[];
  kept: AgentProcessEntry[];
}

export type AgentProcessClassification = "dead" | "recycled" | "live-matching";

let registryHomeOverride: string | null = null;

/**
 * Outcome of a registry read that distinguishes "there is nothing recorded"
 * (ENOENT) from "the file exists but I could not use it".
 *
 * The distinction is load-bearing: a writer that treats EACCES/EIO/corruption
 * as "empty registry" writes back only its own new entry, silently erasing
 * every other live child's record and making those processes untrackable.
 */
export type AgentProcessRegistryReadResult =
  | { ok: true; entries: AgentProcessEntry[]; quarantinedPath?: string }
  | { ok: false; reason: "unreadable"; error: unknown };

/**
 * Pin the registry to one daemon home. `createPaseoDaemon` calls this with
 * `config.paseoHome` so spawn-time recording and startup reaping agree on the
 * daemon's home even when tests pass an explicit `paseoHome` without setting
 * `PASEO_HOME` in the environment. Pass `null` to fall back to env resolution.
 */
export function setAgentProcessRegistryHome(home: string | null): void {
  registryHomeOverride = home;
}

/**
 * Registry path follows the daemon's home so spawn-time recording and startup
 * reaping always agree on one file.
 */
export function resolveAgentProcessRegistryPath(): string {
  return path.join(registryHomeOverride ?? resolvePaseoHome(), AGENT_PROCESS_REGISTRY_FILE);
}

/**
 * Identity of the daemon process recording entries right now. One random value
 * per process: after a daemon restart every existing record belongs to a
 * previous generation, which is what lets the reaper tell this daemon's live
 * records apart from unowned orphans.
 */
const ownerDaemonId = randomUUID();

export function getAgentProcessOwnerDaemonId(): string {
  return ownerDaemonId;
}

/**
 * Move an unusable registry aside instead of overwriting it, so the corrupt
 * content survives for an operator while the next write starts clean.
 */
function quarantineCorruptRegistry(filePath: string, logger?: Logger): string | undefined {
  // The random suffix keeps two corrupt snapshots in the same millisecond from
  // colliding on one name (rename would silently discard the first).
  const quarantinedPath = `${filePath}.corrupt-${Date.now()}-${randomUUID().slice(0, 8)}`;
  try {
    renameSync(filePath, quarantinedPath);
    logger?.error(
      { filePath, quarantinedPath },
      "Agent process registry was unreadable; moved aside so live records are not overwritten",
    );
    return quarantinedPath;
  } catch (error) {
    logger?.error(
      { err: error, filePath },
      "Failed to move corrupt agent process registry aside; refusing to overwrite it",
    );
    return undefined;
  }
}

/**
 * Strict read: ENOENT and corrupt content are recoverable (empty / quarantined),
 * but an I/O or permission failure is an error the caller must not paper over
 * by writing a registry that contains only its own entry.
 */
function readAgentProcessRegistryStrict(
  options: AgentProcessRegistryOptions = {},
): AgentProcessRegistryReadResult {
  const filePath = options.filePath ?? resolveAgentProcessRegistryPath();
  const logger = options.logger;
  let raw: string;
  try {
    raw = readFileSync(filePath, "utf8");
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    if (code === "ENOENT" || code === "ENOTDIR") {
      return { ok: true, entries: [] };
    }
    return { ok: false, reason: "unreadable", error };
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    logger?.error({ filePath }, "Agent process registry is not valid JSON");
    const quarantinedPath = quarantineCorruptRegistry(filePath, logger);
    return quarantinedPath
      ? { ok: true, entries: [], quarantinedPath }
      : { ok: false, reason: "unreadable", error: new Error("corrupt registry") };
  }
  const result = AgentProcessRegistrySchema.safeParse(parsed);
  if (!result.success) {
    logger?.error(
      { filePath, issues: result.error.issues },
      "Agent process registry has an unexpected shape",
    );
    const quarantinedPath = quarantineCorruptRegistry(filePath, logger);
    return quarantinedPath
      ? { ok: true, entries: [], quarantinedPath }
      : { ok: false, reason: "unreadable", error: result.error };
  }
  return { ok: true, entries: result.data };
}

/**
 * Read the registry. A missing file yields []; a corrupt file is moved aside
 * (also yielding []); an unreadable-but-present file yields [] as well so
 * read-only callers keep working, but writers use the strict form above and
 * refuse to write over it.
 */
export function readAgentProcessRegistry(
  options: AgentProcessRegistryOptions = {},
): AgentProcessEntry[] {
  const read = readAgentProcessRegistryStrict(options);
  if (read.ok) {
    return read.entries;
  }
  options.logger?.warn(
    { err: read.error, filePath: options.filePath ?? resolveAgentProcessRegistryPath() },
    "Failed to read agent process registry",
  );
  return [];
}

/**
 * Write the registry durably: the payload is fsync'd before the rename so a
 * crash cannot leave a renamed-but-empty file that would erase every record.
 */
function writeAgentProcessRegistryFile(filePath: string, entries: AgentProcessEntry[]): void {
  writePrivateFileAtomicSync(filePath, `${JSON.stringify(entries, null, 2)}\n`, { fsync: true });
}

/**
 * Identity of a registry record.
 *
 * The pid alone is NOT an identity, and treating it as one is the same defect as
 * keying a reap on the pid: a pid is a reusable slot. Once Linux wraps
 * `pid_max` it hands the recorded main pid to an unrelated process, and if the
 * first scope's members are still running (under `KillMode=process` they usually
 * are), a pid-keyed write replaces that first record and its scope loses the only
 * handle anything has on it.
 *
 * `scopeId` is the real identity, and the whole file already treats it as one:
 * it is the validated half of the signalling target (`unit === scopeId + ".scope"`,
 * matched against `AGENT_SCOPE_ID_PATTERN`), it is what every liveness check asks
 * about (`cgroupHasScope`, `hasForeignScope`), and it is what the daemon signals
 * (`systemctl --user kill --kill-whom=all -- <scopeId>.scope`). No path in this
 * module ever signals by pid. Keying writes on the same pair the kill path uses
 * keeps the two from disagreeing about which record a given child belongs to.
 *
 * The alternative — refusing to write while the incumbent's scope is still
 * populated — was rejected: it discards the NEW record, which leaves the freshly
 * spawned child untracked instead, and it would put a `systemctl` fork on the
 * spawn hot path.
 */
function isSameRecord(left: AgentProcessEntry, right: AgentProcessEntry): boolean {
  return left.pid === right.pid && left.scopeId === right.scopeId;
}

/**
 * Add (or replace) the entry for a pid + scope pair. Never throws: on any failure
 * the registry simply has no entry recorded.
 */
export function recordAgentProcess(
  entry: AgentProcessEntry,
  options: AgentProcessRegistryOptions = {},
): boolean {
  const filePath = options.filePath ?? resolveAgentProcessRegistryPath();
  const logger = options.logger;
  try {
    const validated = AgentProcessEntrySchema.parse(entry);
    // Stamp the recording daemon so startup reaping can tell this daemon's own
    // records from entries whose owning daemon generation is gone.
    const stamped: AgentProcessEntry = {
      ...validated,
      ownerDaemonId: validated.ownerDaemonId ?? ownerDaemonId,
    };
    const current = readAgentProcessRegistryStrict({ filePath, logger });
    if (!current.ok) {
      // Writing now would replace a registry we could not read with a
      // single-entry file, erasing every other live child's record.
      logger?.error(
        { err: current.error, filePath, pid: entry.pid },
        "Refusing to record agent process: registry unreadable, existing records preserved",
      );
      return false;
    }
    // Upsert on (pid, scopeId): re-recording one scope's child refreshes that
    // record and leaves every other scope's record — including one that shares
    // this pid — untouched.
    const next = current.entries.filter((existing) => !isSameRecord(existing, stamped));
    next.push(stamped);
    writeAgentProcessRegistryFile(filePath, next);
    return true;
  } catch (error) {
    logger?.warn({ err: error, filePath, pid: entry.pid }, "Failed to record agent process");
    return false;
  }
}

/**
 * Drop the entry for a pid, optionally narrowed to one scope (idempotent).
 * Never throws.
 *
 * `scopeId` is not optional in practice: forgetting by pid alone removes EVERY
 * record carrying that pid, so once two scopes can share a pid (see
 * `isSameRecord`) a bare `forgetAgentProcess(pid)` from one scope's teardown
 * would delete a sibling record whose scope is still populated — reintroducing
 * the exact untrackable leak this module exists to prevent. Callers that know
 * their scope pass it.
 */
export function forgetAgentProcess(
  pid: number,
  options: AgentProcessRegistryOptions & { scopeId?: string } = {},
): boolean {
  const filePath = options.filePath ?? resolveAgentProcessRegistryPath();
  const logger = options.logger;
  const { scopeId } = options;
  try {
    const current = readAgentProcessRegistryStrict({ filePath, logger });
    if (!current.ok) {
      logger?.error(
        { err: current.error, filePath, pid },
        "Refusing to forget agent process: registry unreadable, existing records preserved",
      );
      return false;
    }
    const next = current.entries.filter(
      (entry) => entry.pid !== pid || (scopeId !== undefined && entry.scopeId !== scopeId),
    );
    if (next.length === current.entries.length) {
      return true;
    }
    writeAgentProcessRegistryFile(filePath, next);
    return true;
  } catch (error) {
    logger?.warn({ err: error, filePath, pid }, "Failed to forget agent process");
    return false;
  }
}

export function isPidAlive(pid: number): boolean {
  if (!Number.isInteger(pid) || pid <= 0) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch (error) {
    // EPERM means the pid exists but belongs to another user — still alive.
    return (error as NodeJS.ErrnoException).code === "EPERM";
  }
}

/**
 * A zombie still answers `kill(pid, 0)`, but it holds no memory, no fds and no
 * CPU and it is already dead for every purpose that matters here: it will never
 * run another instruction and its parent (or init) reaps it without help. A
 * signalled orphan that has become a zombie has therefore been stopped, and
 * waiting any longer would only block the reaper for nothing.
 */
export function isPidZombie(pid: number): boolean {
  if (process.platform !== "linux") return false;
  try {
    const stat = readFileSync(`/proc/${pid}/stat`, "utf8");
    // "pid (comm) state" — comm can contain spaces and parentheses, so the
    // state letter is the one after the final ')'.
    const closing = stat.lastIndexOf(")");
    if (closing < 0) return false;
    return stat
      .slice(closing + 1)
      .trim()
      .startsWith("Z");
  } catch {
    return false;
  }
}

/** True only while the process can still consume CPU. */
export function isPidRunning(pid: number): boolean {
  return isPidAlive(pid) && !isPidZombie(pid);
}

/**
 * Whether this entry's unit may be signalled. The name is data read from a JSON
 * file under `$PASEO_HOME` and is handed to `systemctl --user kill`, so an
 * unvalidated name would let a tampered registry terminate an arbitrary user
 * unit. Only the exact shape `buildAgentScopeInvocation` generates is accepted,
 * and the unit must be that scope's own unit.
 */
export function isSignalableAgentScopeUnit(entry: AgentProcessEntry): boolean {
  return AGENT_SCOPE_ID_PATTERN.test(entry.scopeId) && entry.unit === `${entry.scopeId}.scope`;
}

export type AgentScopeKillSignal = "SIGTERM" | "SIGKILL";

/**
 * Whether an entry's scope cgroup still holds anything that can run.
 *
 * `known: false` means "cannot tell", never "empty". Every caller treats an
 * unmeasurable scope as *possibly populated* so an unreadable scope can never
 * be the reason a record is deleted while something is still running in it.
 */
export interface AgentScopePopulation {
  known: boolean;
  /**
   * True when the scope cgroup, or any cgroup below it, still holds a process.
   * Read from `cgroup.events`' `populated` key rather than from `cgroup.procs`
   * so descendant cgroups count — a scope whose own cgroup is empty but which
   * spawned a sub-cgroup is still not safe to forget.
   */
  populated: boolean;
  /** Member pids, for logs and test assertions only. Never used to signal. */
  pids: number[];
  /** Why the population could not be read. Present only when `known` is false. */
  reason?: string;
}

/** Reads whether an entry's scope is still populated. Test seam and real impl. */
export type AgentScopePopulationReader = (entry: AgentProcessEntry) => AgentScopePopulation;

/**
 * A population answer for an entry that provably has no scope of its own.
 *
 * `spawnInAgentScope` only records a child it actually put in a scope, so an
 * entry whose unit name is not a scope this daemon could have created has no
 * members to lose track of and pid liveness is the whole truth. Without this,
 * a host with no systemd user session would keep every dead record forever just
 * because the cgroup could not be read.
 */
function unpopulatedScope(reason: string): AgentScopePopulation {
  return { known: true, populated: false, pids: [], reason };
}

/** `populated` value from a `cgroup.events` file, or null when unreadable. */
function readCgroupPopulated(eventsPath: string): boolean | null {
  let raw: string;
  try {
    raw = readFileSync(eventsPath, "utf8");
  } catch {
    return null;
  }
  for (const line of raw.split("\n")) {
    const match = /^populated\s+([01])$/.exec(line.trim());
    if (match) return match[1] === "1";
  }
  return null;
}

/** Pids listed in a `cgroup.procs` file, or null when unreadable. */
function readCgroupProcs(procsPath: string): number[] | null {
  let raw: string;
  try {
    raw = readFileSync(procsPath, "utf8");
  } catch {
    return null;
  }
  return raw
    .split("\n")
    .map((line) => Number.parseInt(line.trim(), 10))
    .filter((pid) => Number.isInteger(pid) && pid > 0);
}

/**
 * Turn a systemd `ControlGroup` value into an absolute directory that is
 * provably inside `CGROUP_ROOT`.
 *
 * The value is systemd's own answer for a unit name that already passed
 * `isSignalableAgentScopeUnit`, so it is not attacker-chosen — but it is still
 * used to build a filesystem path, so it gets checked rather than trusted:
 * absolute only, no `..` traversal, no control characters (which is where a NUL
 * or an embedded newline would come from), and the resolved result must still
 * start inside the cgroup mount. Returns null for anything else.
 *
 * A character allowlist is deliberately NOT used here: real systemd paths carry
 * `@` (`user@1000.service`) and backslash escapes, and a list that misses one of
 * them fails closed on the host where the feature is supposed to work.
 */
function resolveCgroupDirectory(controlGroup: string): string | null {
  if (!controlGroup.startsWith("/")) return null;
  if (controlGroup.includes("..")) return null;
  if (hasControlCharacter(controlGroup)) return null;
  const directory = path.resolve(CGROUP_ROOT, `.${controlGroup}`);
  return directory.startsWith(`${CGROUP_ROOT}/`) ? directory : null;
}

/** Any C0 control character or DEL — where an embedded NUL or newline comes from. */
function hasControlCharacter(value: string): boolean {
  for (let index = 0; index < value.length; index += 1) {
    const code = value.charCodeAt(index);
    if (code < 0x20 || code === 0x7f) return true;
  }
  return false;
}

/**
 * Resolve a unit's cgroup directory, or one of the three states the population
 * read needs: absent (no cgroup at all), resolved, or unknown (could not tell).
 *
 * `systemctl show --value` prints exactly one line for the single unit argument,
 * and an empty line for a unit that is not loaded. Since only a single
 * already-validated unit name is ever passed here there is no cross-unit
 * alignment to get wrong; `--` is passed anyway so a name could never be read as
 * an option.
 */
type ResolvedUnitCgroup =
  | { state: "absent" }
  | { state: "resolved"; directory: string }
  | { state: "unknown"; reason: string };

function resolveUnitCgroup(unit: string): ResolvedUnitCgroup {
  let stdout: string;
  try {
    stdout = execFileSync(
      "systemctl",
      ["--user", "show", "--property=ControlGroup", "--value", "--", unit],
      { stdio: ["ignore", "pipe", "pipe"], timeout: 10_000, maxBuffer: SYSTEMCTL_MAX_BUFFER_BYTES },
    ).toString();
  } catch (error) {
    return { state: "unknown", reason: `systemctl show failed: ${String(error)}` };
  }
  const controlGroup = stdout.trim();
  // No ControlGroup means systemd has no cgroup for this unit. Measured on
  // systemd 259: the cgroup directory disappears within milliseconds of its
  // last member dying and the unit is then collected (LoadState=not-found), so
  // an empty value is a reliable "nothing is running in this scope". Joining it
  // onto the mount point would otherwise resolve to the cgroup ROOT, which on
  // this host holds hundreds of unrelated pids and would make every scope look
  // permanently populated.
  if (controlGroup === "" || controlGroup === "/") return { state: "absent" };
  const directory = resolveCgroupDirectory(controlGroup);
  if (directory === null) {
    return { state: "unknown", reason: `unusable ControlGroup ${JSON.stringify(controlGroup)}` };
  }
  return { state: "resolved", directory };
}

/**
 * Population of one already-resolved cgroup directory.
 *
 * A missing directory counts as unpopulated only when its parent still exists.
 * Under a cgroup namespace the host-side path can be absent entirely, and
 * treating that as "empty" would be a second way to delete a record whose scope
 * is running.
 */
function populationOfCgroup(directory: string): AgentScopePopulation {
  if (!existsSync(directory)) {
    if (existsSync(path.dirname(directory))) {
      return { known: true, populated: false, pids: [] };
    }
    return {
      known: false,
      populated: true,
      pids: [],
      reason: `neither ${directory} nor its parent exists; cgroup namespace?`,
    };
  }
  const populated = readCgroupPopulated(path.join(directory, "cgroup.events"));
  if (populated === null) {
    return {
      known: false,
      populated: true,
      pids: [],
      reason: `${directory}/cgroup.events unreadable`,
    };
  }
  if (!populated) return { known: true, populated: false, pids: [] };
  const pids = readCgroupProcs(path.join(directory, "cgroup.procs")) ?? [];
  return { known: true, populated: true, pids };
}

/**
 * Real scope-population read. Costs one `systemctl show` (measured 4ms) plus two
 * small file reads, and is called once per registry entry per reap — never on
 * the spawn hot path.
 */
export function readAgentScopePopulation(entry: AgentProcessEntry): AgentScopePopulation {
  if (!isSignalableAgentScopeUnit(entry)) {
    return unpopulatedScope("entry has no scope this daemon created");
  }
  const resolved = resolveUnitCgroup(entry.unit);
  if (resolved.state === "absent") {
    return { known: true, populated: false, pids: [], reason: "unit has no cgroup" };
  }
  if (resolved.state === "unknown") {
    return { known: false, populated: true, pids: [], reason: resolved.reason };
  }
  return populationOfCgroup(resolved.directory);
}

/**
 * Test seam for the scope-population read.
 *
 * The per-pid `/proc/<pid>/cgroup` seam above cannot express "this unit's cgroup
 * still has members" once the main pid is gone, which is exactly the state this
 * fix is about; this override is keyed by entry (and therefore by unit) so that
 * state is reachable from a test without a systemd session.
 */
let scopePopulationReaderOverride: AgentScopePopulationReader | null = null;

export function __setAgentProcessScopePopulationReaderForTests(
  reader: AgentScopePopulationReader | null,
): void {
  scopePopulationReaderOverride = reader;
}

/** The scope-population read in force: the test override, or the real one. */
export function agentScopePopulationReader(): AgentScopePopulationReader {
  return scopePopulationReaderOverride ?? readAgentScopePopulation;
}

/**
 * Last-resort escalation primitive: SIGKILL every task in the scope's own cgroup
 * subtree by writing `cgroup.kill`.
 *
 * It is only ever reached with a `ControlGroup` systemd itself reported for a
 * unit name that already passed `isSignalableAgentScopeUnit`, so it can only
 * ever affect that one scope — never an arbitrary unit. It exists because
 * `systemctl kill --kill-whom=all` needs the unit to still be loaded and covers
 * only the unit's own cgroup, while `cgroup.events`' `populated` is recursive;
 * without this fallback a scope holding a live descendant cgroup would keep its
 * record forever with no way left to clear it. Measured working on systemd 259 /
 * kernel 7.1. Kernels without `cgroup.kill` (< 5.14) fail the write, and the
 * record is kept for the next reap, which is the safe direction.
 */
function killCgroupDirectly(directory: string): void {
  writeFileSync(path.join(directory, "cgroup.kill"), "1");
}

export interface AgentScopeKillResult {
  stopped: boolean;
  reason: string;
}

export interface AgentScopeKillOptions {
  logger?: Logger;
  /** Test seam for the unit kill. Defaults to `systemctl --user kill`. */
  killScope?: (unit: string, signal: AgentScopeKillSignal) => void;
  termGraceMs?: number;
  killTimeoutMs?: number;
  /**
   * Absolute epoch-ms instant the reap's wall-clock budget runs out. Each wait
   * inside the kill is clamped to it, so one stuck entry cannot consume more
   * than the pass budget.
   */
  deadlineAt?: number;
  /** Test seam for the bounded synchronous wait. */
  sleepMs?: (ms: number) => void;
  /** Test seam for the scope-population read. */
  readScopePopulation?: AgentScopePopulationReader;
}

/**
 * Blocking sleep. The reaper is synchronous (it runs inline during bootstrap and
 * on a bounded periodic timer), so waiting for a signalled orphan's cgroup to
 * empty cannot be async.
 */
function sleepSync(ms: number): void {
  if (ms <= 0) return;
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}

function killScopeUnitViaSystemd(unit: string, signal: AgentScopeKillSignal): void {
  // `systemctl stop` and `RuntimeMaxSec` are both no-ops for the processes in a
  // `KillMode=process` scope (measured on systemd 259: `stop` exits 0 with the
  // process still running; `RuntimeMaxSec=3` drives the unit to `failed` with
  // the process still running). The only primitive that actually stops a scope
  // is `systemctl kill`.
  execFileSync(
    "systemctl",
    ["--user", "kill", "--kill-whom=all", `--signal=${signal}`, "--", unit],
    {
      stdio: ["ignore", "ignore", "pipe"],
      timeout: 10_000,
    },
  );
}

/**
 * Wait for the scope cgroup to report itself unpopulated, or for the deadline.
 *
 * This replaces the old pid-only wait, which returned success the instant the
 * MAIN pid died and therefore never escalated a member that ignored SIGTERM to
 * SIGKILL. Liveness is now the scope's, so a dead main pid with live members
 * keeps the loop waiting.
 */
function waitForScopeEmpty(
  read: () => AgentScopePopulation,
  timeoutMs: number,
  deadlineAt: number,
  sleepMs: (ms: number) => void,
): boolean {
  // Check first: an already-empty scope must not cost one poll interval.
  if (!read().populated) return true;
  const deadline = Math.min(Date.now() + Math.max(timeoutMs, 0), deadlineAt);
  while (Date.now() < deadline) {
    sleepMs(Math.min(ORPHAN_LIVENESS_POLL_MS, Math.max(deadline - Date.now(), 0)));
    if (!read().populated) return true;
  }
  return !read().populated;
}

type KillFn = (unit: string, signal: AgentScopeKillSignal) => void;

/**
 * Stop one expired orphan for good: SIGTERM the whole scope, wait out a grace
 * period, then SIGKILL whatever is left, then — if the cgroup is somehow still
 * populated — SIGKILL the cgroup subtree directly.
 *
 * Liveness is the SCOPE's, never the main pid's. Under `KillMode=process`
 * systemd kills nothing else when a scope's main process exits, so a child the
 * provider spawned (an ACP adapter's dev server, a tool it launched) outlives
 * the recorded pid; the old pid-only wait reported success at that moment,
 * dropped the record, and left that member running with nothing left pointing
 * at it.
 *
 * Returns `stopped: true` only after the scope cgroup reports itself empty. The
 * caller must keep the record when this returns false — a record whose scope is
 * still populated is the untrackable leak this whole path exists to prevent.
 */
export function stopExpiredAgentScope(
  entry: AgentProcessEntry,
  options: AgentScopeKillOptions = {},
): AgentScopeKillResult {
  const logger = options.logger;
  if (!isSignalableAgentScopeUnit(entry)) {
    const reason = `refusing to signal ${JSON.stringify(entry.unit)}: not a scope unit this daemon created`;
    logger?.error(
      { unit: entry.unit, scopeId: entry.scopeId, pid: entry.pid, reason: "untrusted-unit-name" },
      reason,
    );
    return { stopped: false, reason };
  }

  const sleepMs = options.sleepMs ?? sleepSync;
  const termGraceMs = options.termGraceMs ?? AGENT_PROCESS_ORPHAN_TERM_GRACE_MS;
  const killTimeoutMs = options.killTimeoutMs ?? AGENT_PROCESS_ORPHAN_KILL_TIMEOUT_MS;
  const deadlineAt = options.deadlineAt ?? Number.POSITIVE_INFINITY;

  // Resolve the cgroup ONCE. The wait loops below then cost two small file
  // reads each and no subprocesses at all, so the escalation stays cheap even
  // though it is synchronous. A caller-supplied reader short-circuits the
  // resolution entirely and is polled instead.
  const scopeRead = options.readScopePopulation;
  const cgroupDirectory = scopeRead ? null : resolveSignalableScopeDirectory(entry, logger);
  const read =
    scopeRead ??
    (cgroupDirectory === null
      ? agentScopePopulationReader()
      : () => populationOfCgroup(cgroupDirectory));
  // The kill loops below poll liveness, so they need a zero-argument read.
  const readNow = (): AgentScopePopulation => read(entry);

  const initial = readNow();
  if (!initial.known) {
    // Cannot prove the scope is empty, so nothing may be forgotten. Keeping the
    // record is the whole point: it is the only handle on whatever is still
    // running in there, and the next pass retries once systemd answers again.
    return {
      stopped: false,
      reason: `scope population unreadable: ${initial.reason ?? "unknown"}`,
    };
  }
  if (!initial.populated) {
    return { stopped: true, reason: "scope cgroup already empty" };
  }

  const useSystemctl = options.killScope === undefined;
  const killScope: KillFn = options.killScope ?? killScopeUnitViaSystemd;
  const signal = makeUnitSignaller(
    entry,
    killScope,
    useSystemctl ? "systemctl" : "injected",
    logger,
  );

  return escalateScopeToEmpty(
    entry,
    { cgroupDirectory, signal },
    readNow,
    termGraceMs,
    killTimeoutMs,
    deadlineAt,
    sleepMs,
    logger,
  );
}

interface ScopeEscalation {
  cgroupDirectory: string | null;
  signal: (signal: AgentScopeKillSignal) => string | null;
}

/**
 * The escalation ladder: SIGTERM the scope, then SIGKILL what is left, then — for
 * a cgroup systemd can no longer act on by name — one direct write of the
 * scope's own `cgroup.kill`. After each step the scope is re-read and the ladder
 * only continues while the cgroup still reports itself populated, so a scope that
 * empties early never reaches the next signal.
 *
 * Returns `stopped: false` when the cgroup is still populated at the end, which
 * is the caller's signal to keep the record for the next reap.
 */
function escalateScopeToEmpty(
  entry: AgentProcessEntry,
  escalation: ScopeEscalation,
  readNow: () => AgentScopePopulation,
  termGraceMs: number,
  killTimeoutMs: number,
  deadlineAt: number,
  sleepMs: (ms: number) => void,
  logger?: Logger,
): AgentScopeKillResult {
  const { cgroupDirectory, signal } = escalation;
  const settle = (timeoutMs: number): string | null =>
    waitForScopeEmpty(readNow, timeoutMs, deadlineAt, sleepMs) ? null : "populated";

  let lastError = signal("SIGTERM");
  const afterTerm = settle(termGraceMs);
  if (afterTerm === null) return { stopped: true, reason: "scope cgroup emptied after SIGTERM" };

  lastError = signal("SIGKILL") ?? lastError;
  const afterKill = settle(killTimeoutMs);
  if (afterKill === null) return { stopped: true, reason: "scope cgroup emptied after SIGKILL" };

  // `systemctl kill` needs the unit loaded and covers only the unit's own
  // cgroup, so it can leave a populated subtree behind. One direct write of the
  // scope's own `cgroup.kill` is the last primitive available, and it is
  // reachable only for a cgroup systemd reported for an already-validated unit.
  lastError = killScopeCgroupDirectly(entry, cgroupDirectory, lastError, logger) ?? lastError;
  const afterDirectKill = settle(killTimeoutMs);
  if (afterDirectKill === null) {
    return { stopped: true, reason: "scope cgroup emptied after a direct cgroup kill" };
  }

  const survivors = readNow();
  return {
    stopped: false,
    reason:
      lastError ??
      `scope cgroup still populated after SIGTERM, SIGKILL and a direct cgroup kill (survivors: ${JSON.stringify(survivors.pids)})`,
  };
}

/**
 * The cgroup path to poll for this entry, or null when it cannot be resolved
 * (in which case the population is re-read per check instead).
 */
function resolveSignalableScopeDirectory(entry: AgentProcessEntry, logger?: Logger): string | null {
  const resolved = resolveUnitCgroup(entry.unit);
  if (resolved.state === "resolved") return resolved.directory;
  logger?.debug?.(
    {
      unit: entry.unit,
      reason: resolved.state === "absent" ? "unit has no cgroup" : resolved.reason,
    },
    "Scope cgroup could not be resolved for polling; re-reading per check",
  );
  return null;
}

function killScopeCgroupDirectly(
  entry: AgentProcessEntry,
  cgroupDirectory: string | null,
  priorError: string | null,
  logger?: Logger,
): string | null {
  if (cgroupDirectory === null) return priorError;
  try {
    killCgroupDirectly(cgroupDirectory);
    return null;
  } catch (error) {
    const detail = `writing cgroup.kill for ${entry.unit} failed: ${String(error)}`;
    logger?.warn({ err: error, unit: entry.unit, cgroupDirectory }, detail);
    return detail;
  }
}

function makeUnitSignaller(
  entry: AgentProcessEntry,
  killScope: KillFn,
  via: string,
  logger?: Logger,
): (signal: AgentScopeKillSignal) => string | null {
  return (signal) => {
    try {
      killScope(entry.unit, signal);
      return null;
    } catch (error) {
      const detail = `systemctl --user kill ${signal} failed: ${String(error)}`;
      logger?.warn({ err: error, unit: entry.unit, pid: entry.pid, signal, via }, detail);
      return detail;
    }
  };
}

interface ProcessIdentity {
  cmdline: string;
  comm: string;
  exe: string;
}

/**
 * Best-effort identity read, same idea as deploy/systemd/paseo-prestart.sh:
 * cmdline + comm (+ exe) is what a recycled pid cannot fake.
 */
function readProcessIdentity(pid: number): ProcessIdentity | null {
  const base = `/proc/${pid}`;
  try {
    const cmdline = readFileSync(`${base}/cmdline`, "utf8").replaceAll("\u0000", " ").trim();
    const comm = readFileSync(`${base}/comm`, "utf8").trim();
    let exe = "";
    try {
      exe = readlinkSync(`${base}/exe`);
    } catch {
      // exe is a symlink that can vanish or be unreadable; it is only extra evidence.
    }
    return { cmdline, comm, exe };
  } catch {
    return null;
  }
}

function matchesProviderMarker(identity: ProcessIdentity, provider: string): boolean {
  const needle = provider.trim().toLowerCase();
  if (!needle) return false;
  const haystack = `${identity.cmdline} ${identity.comm} ${identity.exe}`.toLowerCase();
  return haystack.includes(needle);
}

/**
 * Reads `/proc/<pid>/cgroup`. Overridable in tests: a real process cannot be
 * placed inside a fabricated scope cgroup, so scope-membership scenarios are
 * driven through this reader while liveness and cmdline stay real.
 */
type ProcessCgroupReader = (pid: number) => string | null;

let cgroupReaderOverride: ProcessCgroupReader | null = null;

export function __setAgentProcessCgroupReaderForTests(reader: ProcessCgroupReader | null): void {
  cgroupReaderOverride = reader;
}

function readCgroupDirect(pid: number): string | null {
  try {
    return readFileSync(`/proc/${pid}/cgroup`, "utf8");
  } catch {
    return null;
  }
}

function readProcessCgroup(pid: number): string | null {
  if (cgroupReaderOverride) return cgroupReaderOverride(pid);
  return readCgroupDirect(pid);
}

/**
 * Scope unit name this process itself lives in, or null when it is not in a
 * scope (the normal case: the daemon runs in its unit cgroup). Read from the
 * real /proc, never through the test override. A recorded child spawned by
 * this very process shares our scope; that must not count as "foreign scope".
 * The test runner can itself run inside a scoped agent child, and probes it
 * spawns inherit that scope — treating it as recycled would break marker-based
 * classification in exactly the agent-driven workflow this feature targets.
 */
let ownProcessScope: string | null | undefined;

function getOwnProcessScope(): string | null {
  if (ownProcessScope === undefined) {
    ownProcessScope = extractScopeUnit(readCgroupDirect(process.pid));
  }
  return ownProcessScope;
}

/** First `<name>.scope` path segment in a cgroup text, or null. */
function extractScopeUnit(cgroup: string | null): string | null {
  if (cgroup === null) return null;
  const match = /(?:^|[/\n])([A-Za-z0-9_.:-]+\.scope)(?=[/\n]|$)/.exec(cgroup);
  return match ? match[1] : null;
}

/**
 * True when the pid is a member of the expected transient scope unit. A scope
 * is created only by `spawnInAgentScope`, and a recycled pid cannot fake
 * membership in its cgroup — this is the authoritative child identity. Matched
 * on whole path segments: the unit name is the last segment of the scope's
 * cgroup path, so a prefix of another unit's name must not count.
 */
function cgroupHasScope(cgroup: string, scopeId: string): boolean {
  return extractScopeUnit(cgroup) === `${scopeId}.scope`;
}

/**
 * True when the pid belongs to some scope unit that is neither the expected
 * scope nor this process's own scope. Membership in a different scope proves
 * the pid is not the recorded child (a recorded child lives only in its own
 * scope).
 */
function hasForeignScope(cgroup: string, entry: AgentProcessEntry): boolean {
  const ownScope = getOwnProcessScope();
  const expected = `${entry.scopeId}.scope`;
  const pattern = /(?:^|[/\n])([A-Za-z0-9_.:-]+\.scope)(?=[/\n]|$)/g;
  for (const match of cgroup.matchAll(pattern)) {
    if (match[1] !== expected && match[1] !== ownScope) return true;
  }
  return false;
}

/**
 * May this entry's record be deleted without signalling anything?
 *
 * Only when the scope is PROVABLY unpopulated, or when the entry provably has
 * no scope of its own (which `readAgentScopePopulation` answers with a known,
 * unpopulated set). An unreadable scope is never "empty": the record is the
 * only handle anyone has on whatever is still running in there, so an
 * unmeasurable scope keeps its record.
 *
 * This is the single definition of "dead" in the registry, shared by the
 * reaper (`classifyByScopePopulation`) and the detach-stop flush
 * (`flushLiveAgentProcesses`), so the two pid-first paths cannot drift into
 * disagreeing about what a scope reading means.
 */
function mayForgetScopedEntry(population: AgentScopePopulation): boolean {
  return population.known && !population.populated;
}

/**
 * Classification for an entry the pid path could not speak for.
 *
 * Every "inconclusive pid" outcome funnels through here, so the scope — not the
 * pid — decides. `dead` requires a provably empty scope, and an unmeasurable
 * one (`known: false`) counts as populated on purpose.
 */
function classifyByScopePopulation(
  entry: AgentProcessEntry,
  readScopePopulation: AgentScopePopulationReader,
): AgentProcessClassification {
  return mayForgetScopedEntry(readScopePopulation(entry)) ? "dead" : "live-matching";
}

/**
 * Classification for a pid that is CONCLUSIVELY not the recorded child.
 *
 * A conclusive answer about the pid is still silent about the scope, and the
 * scope — not the pid — is what owns the survivors. Under `KillMode=process` a
 * main process that has been replaced by an unrelated one says nothing at all
 * about what the real child left running behind it. So the same
 * `mayForgetScopedEntry` test that gates `dead` gates this outcome too:
 * `recycled` is removable only once the scope is PROVABLY empty, and a
 * populated or unmeasurable scope keeps the record.
 *
 * Keeping is the safe direction by construction. Signalling is by scope, never
 * by pid, so a retained record can only ever lead to a `systemctl --user kill`
 * aimed at this entry's own validated unit — the unrelated process that happens
 * to hold the pid is never touched either way.
 */
function classifyRecycledPid(
  entry: AgentProcessEntry,
  readScopePopulation: AgentScopePopulationReader,
): AgentProcessClassification {
  return mayForgetScopedEntry(readScopePopulation(entry)) ? "recycled" : "live-matching";
}

/**
 * Classify one registry entry:
 * - dead: the pid path could not identify a live child AND the scope is provably
 *   empty
 * - live-matching: pid is alive and a member of the entry's expected scope, OR
 *   the pid could not speak (gone, no usable identity, or provably not the
 *   recorded child) but the scope still holds something
 * - recycled: pid is alive but provably not the recorded child, AND the scope
 *   is provably empty. No outcome is removable on pid evidence alone: a scope
 *   that still holds a process keeps its record whichever way the pid reads.
 *
 * Identity is decided by cgroup membership first: the ACP spawn site records
 * provider ids like `claude-acp` while launching a different binary
 * (`prefix.command`), so cmdline markers alone can misclassify a live child as
 * recycled and drop its record while the process keeps running. A live pid in
 * the expected scope is therefore never recycled, whatever its cmdline says.
 *
 * A pid in some other scope (not the expected one, not ours) is recycled — it
 * cannot be the recorded child.
 *
 * Marker fallback (cmdline + comm + exe contains the provider id) applies only
 * when scope membership cannot speak for the entry: the expected scope no
 * longer exists (legacy record, unit collected) and the pid carries no foreign
 * scope either. Best effort either way; never applies to a pid alive in its
 * expected scope.
 *
 * An INCONCLUSIVE pid is not proof the scope is empty, and there are two ways to
 * be inconclusive — not just the obvious one:
 *
 * 1. `kill(pid, 0)` fails: the pid is gone entirely.
 * 2. `kill(pid, 0)` SUCCEEDS but the pid carries no usable identity, because a
 *    ZOMBIE still answers signal 0 while `/proc/<pid>/cmdline` is empty (it has
 *    already exited and only its parent's `waitpid` can clear it). An unreadable
 *    `/proc/<pid>` — `hidepid`, or a `PR_SET_DUMPABLE=0` provider — lands on the
 *    same branch, since `readProcessIdentity` returns null.
 *
 * Treating case 2 as `dead` deleted the record with zero signals while the scope
 * was still running, which is precisely the leak this whole path exists to
 * prevent. Both cases now consult the scope, and only a provably empty scope is
 * `dead`.
 *
 * A CONCLUSIVE pid is no safer than an inconclusive one here, and `recycled` is
 * the case that proves it. "This pid is alive and provably not the recorded
 * child" is a statement about ONE process; it says nothing about the scope,
 * which under `KillMode=process` is exactly where the survivors live. Letting it
 * delete the record meant the leak survived every fix above: the instant Linux
 * handed the recorded main pid to an unrelated process, a scope with a live
 * member lost its only handle, with no signal and regardless of how fresh the
 * orphan stamp was. So `recycled` asks the scope too, and a populated or
 * unmeasurable scope keeps the record exactly as it does for a zombie pid.
 *
 * That happens only once the pid path has failed to classify the entry, so a reap
 * of live records still costs no `systemctl` fork per entry.
 */
export function classifyAgentProcessEntry(
  entry: AgentProcessEntry,
  readScopePopulation?: AgentScopePopulationReader,
): AgentProcessClassification {
  // Binding the reader is free — `agentScopePopulationReader()` only returns a
  // reference; the `systemctl show` fork happens when the reader is CALLED.
  const readScope = readScopePopulation ?? agentScopePopulationReader();
  if (!isPidAlive(entry.pid)) {
    return classifyByScopePopulation(entry, readScope);
  }
  if (process.platform !== "linux") {
    // /proc is unavailable; liveness is all we can verify off Linux.
    return "live-matching";
  }
  const identity = readProcessIdentity(entry.pid);
  // No usable identity: a zombie (empty cmdline, still answering `kill(pid, 0)`),
  // a vanished pid, or an unreadable /proc. Not evidence about the scope.
  if (!identity || !identity.cmdline) {
    return classifyByScopePopulation(entry, readScope);
  }
  const cgroup = readProcessCgroup(entry.pid);
  if (cgroup !== null) {
    if (cgroupHasScope(cgroup, entry.scopeId)) return "live-matching";
    if (hasForeignScope(cgroup, entry)) return classifyRecycledPid(entry, readScope);
  }
  return matchesProviderMarker(identity, entry.provider)
    ? "live-matching"
    : classifyRecycledPid(entry, readScope);
}

/** Flush outcome: records kept because the pid is alive, records dropped. */
export interface FlushResult {
  kept: AgentProcessEntry[];
  removed: AgentProcessEntry[];
}

/**
 * Detach-stop flush: drop entries whose pid is gone AND whose scope is provably
 * empty, keep every entry whose pid is still alive or whose scope still holds
 * something (no provider-marker check — a live pid is enough to guarantee the
 * next daemon can look at it; its startup reap decides live-vs-recycled).
 *
 * The scope test is what keeps a survivor trackable across a detach-stop: under
 * `KillMode=process` the main process exiting says nothing about the children it
 * left behind, and dropping the record for those would hand the next daemon
 * nothing to find. Never throws: a registry failure degrades to "nothing
 * flushed".
 */
export function flushLiveAgentProcesses(
  options: AgentProcessRegistryOptions & { readScopePopulation?: AgentScopePopulationReader } = {},
): FlushResult {
  const filePath = options.filePath ?? resolveAgentProcessRegistryPath();
  const logger = options.logger;
  try {
    const read = readAgentProcessRegistryStrict({ filePath, logger });
    if (!read.ok) {
      logger?.warn(
        { err: read.error, filePath },
        "Agent process registry flush skipped: registry unreadable, records preserved",
      );
      return { kept: [], removed: [] };
    }
    const readScopePopulation = options.readScopePopulation ?? agentScopePopulationReader();
    const entries = read.entries;
    const kept: AgentProcessEntry[] = [];
    const removed: AgentProcessEntry[] = [];
    for (const entry of entries) {
      const keep = isPidAlive(entry.pid) || !mayForgetScopedEntry(readScopePopulation(entry));
      (keep ? kept : removed).push(entry);
    }
    if (removed.length > 0) {
      writeAgentProcessRegistryFile(filePath, kept);
    }
    logger?.info(
      { filePath, kept: kept.length, removed: removed.length },
      "Agent process registry flushed for detach stop",
    );
    return { kept, removed };
  } catch (error) {
    logger?.warn({ err: error, filePath }, "Agent process registry flush failed; continuing");
    return { kept: [], removed: [] };
  }
}

/**
 * Startup reaper, and the daemon's only bounded kill path for scoped children.
 *
 * SYNCHRONOUS on purpose. The registry is a read-modify-write JSON file with no
 * cross-process lock, so a reap that yielded between its read and its
 * write-back could clobber a record written by a concurrent spawn. The
 * wall-clock cost is bounded instead: `budgetMs` caps the whole pass, including
 * the waits inside each kill, and entries not reached are kept for the next
 * pass rather than dropped.
 *
 * Per entry:
 * - `dead` — drop the record, never signal: the pid is gone and the scope is
 *   provably empty.
 * - `recycled` — drop the record, never signal. The pid is alive but provably
 *   not the recorded child, so it is not ours to touch. This outcome now also
 *   requires a provably empty scope (see `classifyRecycledPid`), so dropping
 *   here means the scope holds nothing — exactly the `dead` guarantee.
 * - `live-matching`, owned by this daemon — keep, never signal. This is a child
 *   of the running daemon; it may be a legitimately long-lived agent. It stays
 *   reapable: if this daemon exits, the next one sees it as an orphan.
 * - `live-matching`, not owned by this daemon — stamp `orphanedAt` the first time
 *   we see it (the orphan clock starts now, not at `startedAt`) and keep it while
 *   it is inside the TTL. Past the TTL it is a genuine orphan: stop it, and only
 *   drop the record once its scope cgroup is confirmed empty. If the kill fails
 *   the record is KEPT so the next reap retries — a live child must never lose
 *   its record, because that is exactly what makes it unkillable forever.
 *
 * Never throws: a registry failure degrades to "nothing reaped", never a crash.
 */
export function reapStaleAgentProcesses(
  options: AgentProcessRegistryOptions & AgentScopeKillOptions & { budgetMs?: number } = {},
): ReapResult {
  const filePath = options.filePath ?? resolveAgentProcessRegistryPath();
  const logger = options.logger;
  try {
    const read = readAgentProcessRegistryStrict({ filePath, logger });
    if (!read.ok) {
      logger?.warn(
        { err: read.error, filePath },
        "Agent process registry reap skipped: registry unreadable, records preserved",
      );
      return { removed: [], kept: [] };
    }
    const readScopePopulation = options.readScopePopulation ?? agentScopePopulationReader();
    const deadlineAt =
      options.budgetMs === undefined
        ? Number.POSITIVE_INFINITY
        : Date.now() + Math.max(options.budgetMs, 0);
    const removed: AgentProcessEntry[] = [];
    const kept: AgentProcessEntry[] = [];
    let restamped = false;
    let deferred = 0;
    for (const entry of read.entries) {
      if (Date.now() >= deadlineAt) {
        // Out of budget: keep the rest exactly as they are. The reaper blocks
        // the event loop while it waits, so a pass must never be able to run
        // unbounded no matter how many stuck entries the registry holds.
        kept.push(entry);
        deferred += 1;
        continue;
      }
      const decision = decideReapForEntry(entry, {
        filePath,
        logger,
        deadlineAt,
        kill: { ...options, readScopePopulation },
      });
      if (decision.disposition === "keep") {
        kept.push(decision.entry);
        restamped = restamped || decision.restamped;
        continue;
      }
      if (decision.disposition === "keep-unlogged") {
        kept.push(decision.entry);
        continue;
      }
      removed.push(decision.entry);
      restamped = true;
    }
    if (read.quarantinedPath !== undefined || removed.length > 0 || restamped) {
      writeAgentProcessRegistryFile(filePath, kept);
    }
    if (deferred > 0) {
      logger?.warn(
        { filePath, deferred, budgetMs: options.budgetMs },
        "Agent process registry reap hit its wall-clock budget; the remaining entries were kept for the next pass",
      );
    }
    logger?.info(
      { filePath, removed: removed.length, kept: kept.length },
      "Agent process registry reaped",
    );
    return { removed, kept };
  } catch (error) {
    logger?.warn({ err: error, filePath }, "Agent process registry reap failed; continuing");
    return { removed: [], kept: [] };
  }
}

type ReapDecision =
  /** Keep the entry as-is (already logged, or nothing to say). */
  | { disposition: "keep-unlogged"; entry: AgentProcessEntry }
  /** Keep the entry, optionally with a fresh `orphanedAt` stamp. */
  | { disposition: "keep"; entry: AgentProcessEntry; restamped: boolean }
  /** The record can go: nothing is running in its scope. */
  | { disposition: "remove"; entry: AgentProcessEntry };

function decideReapForEntry(
  entry: AgentProcessEntry,
  ctx: {
    filePath: string;
    logger?: Logger;
    deadlineAt: number;
    kill: AgentScopeKillOptions & { readScopePopulation: AgentScopePopulationReader };
  },
): ReapDecision {
  const { filePath, logger } = ctx;
  const population = ctx.kill.readScopePopulation(entry);
  const classification = classifyAgentProcessEntry(entry, () => population);
  if (classification === "recycled") {
    // Alive but provably not the recorded child, so it is not ours to touch.
    // `classifyAgentProcessEntry` reached "recycled" only after the same
    // `mayForgetScopedEntry` test that gates "dead" — so a populated or
    // unmeasurable scope never lands here and this branch, like "dead", means
    // "the scope is provably empty". Keeping the gate in the classifier rather
    // than repeating it here is deliberate: it is one predicate, one place, and
    // every caller of the exported classifier inherits it.
    logger?.info(
      { filePath, pid: entry.pid, provider: entry.provider, unit: entry.unit, classification },
      "Reaped stale agent process registry entry",
    );
    return { disposition: "remove", entry };
  }
  if (classification === "dead") {
    // `classifyAgentProcessEntry` reached "dead" only after an unpopulated or
    // unmeasurable scope was ruled out, and an unmeasurable scope is reported as
    // populated on purpose — so this branch is exactly "the scope is provably
    // empty" and the record is pure bookkeeping. This is the only branch in the
    // daemon that deletes a scoped record without signalling first.
    logger?.info(
      { filePath, pid: entry.pid, provider: entry.provider, unit: entry.unit, classification },
      "Reaped stale agent process registry entry",
    );
    return { disposition: "remove", entry };
  }

  // Owned by this daemon: keep and never signal. This is a child of the running
  // daemon and may be a legitimately long-lived agent — including one whose main
  // process has exited while a child it started is still alive. The record is
  // kept, so it stays reapable: when this daemon exits, the next one adopts it
  // as an orphan and stops it for real.
  if (entry.ownerDaemonId === ownerDaemonId) {
    return { disposition: "keep-unlogged", entry };
  }

  const now = Date.now();
  if (!entry.orphanedAt) {
    // First observation as unowned starts the orphan clock. Stamping on first
    // sight is what keeps a long-running child from being expired by its own age
    // in the very next bootstrap after its owner died.
    logger?.info(
      {
        filePath,
        scopeId: entry.scopeId,
        unit: entry.unit,
        pid: entry.pid,
        provider: entry.provider,
        startedAt: entry.startedAt,
        ttlMs: AGENT_PROCESS_UNOWNED_RECORD_TTL_MS,
        reason: "orphaned",
      },
      "Unowned agent scope record adopted as an orphan clock started",
    );
    return {
      disposition: "keep",
      entry: { ...entry, orphanedAt: new Date(now).toISOString() },
      restamped: true,
    };
  }

  const orphanAgeMs = now - Date.parse(entry.orphanedAt);
  if (Number.isFinite(orphanAgeMs) && orphanAgeMs <= AGENT_PROCESS_UNOWNED_RECORD_TTL_MS) {
    return { disposition: "keep-unlogged", entry };
  }

  const kill = stopExpiredAgentScope(entry, { ...ctx.kill, deadlineAt: ctx.deadlineAt });
  const baseLog = {
    filePath,
    scopeId: entry.scopeId,
    unit: entry.unit,
    pid: entry.pid,
    provider: entry.provider,
    startedAt: entry.startedAt,
    orphanedAt: entry.orphanedAt,
    orphanAgeMs: Number.isFinite(orphanAgeMs) ? orphanAgeMs : null,
  };
  if (!kill.stopped) {
    // Keep the record: an orphan we could not stop is exactly the case where
    // deleting the bookkeeping would make it unkillable forever.
    logger?.error(
      { ...baseLog, reason: "orphan-kill-failed", detail: kill.reason },
      `Failed to stop expired agent scope orphan ${entry.unit} (pid ${entry.pid}); keeping its record for the next reap`,
    );
    return { disposition: "keep-unlogged", entry };
  }
  logger?.warn(
    { ...baseLog, stoppedBy: kill.reason, reason: "orphan-stopped" },
    `Stopped expired orphan agent scope ${entry.unit} (pid ${entry.pid}) and dropped its record`,
  );
  return { disposition: "remove", entry };
}
