packages:
  - "packages/*"
allowBuilds:
  dtrace-provider: set this to true or false
  electron: set this to true or false
  electron-winstaller: set this to true or false
  esbuild: set this to true or false
  lefthook: set this to true or false
  node-pty: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
  workerd: set this to true or false
