packages:
  - "packages/*"
allowBuilds:
  '@parcel/watcher': true
  dtrace-provider: true
  electron: true
  electron-winstaller: true
  esbuild: true
  lefthook: true
  node-pty: true
  sharp: true
  unrs-resolver: true
  workerd: true
