// Plugin build step (runs from the staged plugin dir after `npm install`).
//
// 1. Copy the adapter source from packages/freebuff-acp (this plugin lives in
//    the same repository) so tsc resolves dependencies from this dir's
//    node_modules.
// 2. Compile it to dist/ (type errors are the adapter package's own gate).
// 3. Verify the vendored @codebuff/sdk fork supports per-run `extraCodebuffMetadata`.
// 4. Generate server/generated.ts with the absolute path of dist/entry.js,
//    because the server bundle does not know where the plugin dir is.
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const pluginDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const adapterSource = path.resolve(pluginDir, "../../packages/freebuff-acp/src");
const stagedSource = path.join(pluginDir, "adapter-src");
const distDir = path.join(pluginDir, "dist");

function fail(message) {
  console.error(`freebuff plugin build: ${message}`);
  process.exit(1);
}

if (!fs.existsSync(adapterSource)) fail(`adapter source not found at ${adapterSource}`);

fs.rmSync(stagedSource, { recursive: true, force: true });
fs.rmSync(distDir, { recursive: true, force: true });
fs.cpSync(adapterSource, stagedSource, {
  recursive: true,
  filter: (source) => !source.endsWith(".test.ts"),
});

const tsc = path.join(pluginDir, "node_modules", "typescript", "bin", "tsc");
const compiled = spawnSync(
  process.execPath,
  [tsc, "-p", "tsconfig.adapter.json", "--noCheck", "--incremental", "false"],
  { cwd: pluginDir, stdio: "inherit" },
);
if (compiled.status !== 0) fail("tsc failed");
fs.writeFileSync(path.join(distDir, "package.json"), '{"type":"module"}\n');

// The fork SDK (vendor/) carries the official per-run `extraCodebuffMetadata`
// option; fail the build if a swapped-in SDK does not, instead of patching it.
for (const file of ["index.mjs", "index.cjs"]) {
  const target = path.join(pluginDir, "node_modules", "@codebuff", "sdk", "dist", file);
  if (!fs.existsSync(target)) fail(`SDK file missing: ${target}`);
  if (!fs.readFileSync(target, "utf8").includes("extraCodebuffMetadata")) {
    fail(`${file}: @codebuff/sdk lacks extraCodebuffMetadata; use the vendored fork build`);
  }
}

const entry = path.join(distDir, "entry.js");
const cli = path.join(distDir, "cli.js");
fs.writeFileSync(
  path.join(pluginDir, "server", "generated.ts"),
  `// Generated by scripts/build.mjs — do not edit.\n` +
    `export const ADAPTER_ENTRY = ${JSON.stringify(entry)};\n` +
    `export const ADAPTER_CLI = ${JSON.stringify(cli)};\n`,
);
console.log(`freebuff plugin build: ok (${entry})`);
